# Generated by Django 5.2.4 on 2025-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adharno', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('disease', models.CharField(choices=[('flu', 'Flu'), ('covid', 'COVID-19'), ('diabetes', 'Diabetes'), ('bp', 'Blood Pressure'), ('other', 'Other')], max_length=20)),
                ('city', models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
    ]
